apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3 # Number of instances to run
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: asia-east1-docker.pkg.dev/iti-final-project-403406/my-repository/hello-world-app:latest  # Image name and tag
        ports:
        - containerPort: 5000  # Port on which Flask app is running
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 5000  # Port on which Flask app is running inside the pods
  type: LoadBalancer  # Expose the service externally using a Load Balancer
